Algoritmo "anos_caninos"

Var
idade_humana: inteiro
idade_canina: inteiro


Inicio

escreval ("Descubra a idade humana do seu doguinho!")
escreva ("Digite a idade canina dele: ")
leia (idade_canina)

escreval ("-----------------------------------------------------------")
escreval ("1 ano canino - 15 anos humanos")
escreval ("2 anos caninos - 9 anos humanos")
escreval ("a partir de 3 anos caninos, cada anos conta 5 anos humanos")
escreval ("-----------------------------------------------------------")

limpatela

se idade_canina = 1 entao
    escreval ("Seu doguinho tem 15 anos humanos")
senao
    se idade_canina = 2 entao
        idade_humana <- 15 + 9
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 3 entao
        idade_humana <- 15 + 9 + 5
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 4 entao
        idade_humana <- (15 + 9) + 5 * 2
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 5 entao
        idade_humana <- (15 + 9) + 5 * 3
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 6 entao
        idade_humana <- (15 + 9) + 5 * 4
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 7 entao
        idade_humana <- (15 + 9) + 5 * 5
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 8 entao
        idade_humana <- (15 + 9) + 5 * 6
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 9 entao
        idade_humana <- (15 + 9) + 5 * 7
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 10 entao
        idade_humana <- (15 + 9) + 5 * 8
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 11 entao
        idade_humana <- (15 + 9) + 5 * 9
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 12 entao
        idade_humana <- (15 + 9) + 5 * 10
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 13 entao
        idade_humana <- (15 + 9) + 5 * 11
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 14 entao
        idade_humana <- (15 + 9) + 5 * 12
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 15 entao
        idade_humana <- (15 + 9) + 5 * 13
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 16 entao
        idade_humana <- (15 + 9) + 5 * 14
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 17 entao
        idade_humana <- (15 + 9) + 5 * 15
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 18 entao
        idade_humana <- (15 + 9) + 5 * 16
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 19 entao
        idade_humana <- (15 + 9) + 5 * 17
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")
senao
    se idade_canina = 20 entao
        idade_humana <- (15 + 9) + 5 * 18
    escreval ("Seu doguinho tem", idade_humana, " anos humanos")



fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse



Fimalgoritmo