Algoritmo "aula1_hello_world"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Kleber Lucas
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Leonardo De Oliveira Julião
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
nome: CARACTERE
profissao: caractere
idade: INTEIRO
altura: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Hello World")
escreval("Leonardo De Oliveira Julião")
escreval("Tenho 27 anos")
//Atribuição de variáveis
nome <- "Peter Parker"
profissao <- "Fotógrafo"
idade <- 17
altura <- 1.78

//Mostrando variável em um Output
escreval ("O nome é: ", nome)
escreval ("Ele tem", idade, " anos")
escreval ("A altura dele é", altura, "m")
Fimalgoritmo