Algoritmo "variaveis_no_output"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Kleber Lucas
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Leonardo De Oliveira Julião
// Data atual  : 17/04/2026
Var
// Seção de Declarações das variáveis 
nome_do_produto: caractere
preco_do_produto: caractere
cor_do_produto: caractere
capacidade_interna: caractere
memoria_ram: caractere

Inicio
//Atribuição da variável
nome_do_produto <- "Macbook Air M5"
preco_do_produto <- "R$ 8.000,00"
cor_do_produto <- "Midnight"
capacidade_interna <- "1Tb"
memoria_ram <- "16gb"

//Mostrando as variáveis no Output
escreval ("Produto: ", nome_do_produto)
escreval ("Valor: ", preco_do_produto)
escreval ("Cor: ", cor_do_produto)
escreval ("Capacidade interna: ", capacidade_interna)
escreval ("Memória RAM: ", memoria_ram)
Fimalgoritmo